### PR TITLE
order table list with click collumn #283

### LINKED ISSUE #283: order table list with click collumn
By default, we should display the list sorted by the available nodes first (server up in the "Is it Up?" column), ordered by the number of Peers, and then alphabetically. 

With the exception of the Endpoint column, all the other fields should be sortable and then ordered by number of peers, and then alphabetically. If users change the sort order themselves, we will not revert it back to default until the page is refreshed.

### PR DESCRIPTION
**Pull request by endkeyCoder**

### CODE REVIEW

File: src/constants.tsx [hunk 1]
```diff
@@ -3,13 +3,15 @@ import { Icon } from '@iconify/react'
...
 
+import './components/navigation/Sidebar.scss'
 import { store } from './store'
 import { ReactComponent as Home } from './assets/icons/home.svg'
 import { ReactComponent as Transactions } from './assets/icons/transactions.svg'
 import { ReactComponent as Blocks } from './assets/icons/blocks.svg'
 import { ReactComponent as Wallets } from './assets/icons/wallets.svg'
 import { ReactComponent as Api } from './assets/icons/api.svg'
 import { ReactComponent as Magnify } from './assets/icons/magnify.svg'
+import Monitor from './assets/icons/monitor.png'
```
Comment (comountainclimber) [inline src/constants.tsx:14]: Please use an svg here (replicate the pattern used for every other route)

Comment (comountainclimber) [reply src/constants.tsx:14]: https://cityofzion.slack.com/archives/C01LS9M9A84/p1618009962000100

File: src/pages/monitor/Monitor.tsx [hunk 2]
```diff
@@ -0,0 +1,399 @@
...
+interface StateHeight extends AllNodes {
+  text: string
+}
+
+const StateHeight: React.FC<StateHeight> = ({ text, disable }) => {
+  return <div className={disable ? 'disable' : ''}>{text}</div>
+}
+
+const mapNodesData = (data: WSDoraData): ParsedNodes => {
+  const isPositive = (): boolean => {
```
Comment (comountainclimber) [inline src/pages/monitor/Monitor.tsx:154]:
```suggestion
const isPositive = (): boolean =>
  data.status === 'ok' ||
  data.status === 'stateheight stalled' ||
  data.status === 'stateheight lagging'

```

Comment (comountainclimber) [reply src/pages/monitor/Monitor.tsx:154]: Small style suggestion

File: src/pages/monitor/Monitor.tsx [hunk 3]
```diff
@@ -0,0 +1,399 @@
...
+    setAvgBlockTime((sumBlockTime / listAvgBlockTime.length).toFixed(1))
+  }, [listAvgBlockTime])
+
+  useEffect(() => {
+    handleLastBlock()
+  }, [])
+
+  useEffect(() => {
+    setBestBlock(getBestBlock()) //eslint-disable-next-line
+  }, [nodes])
```
Comment (comountainclimber) [inline src/pages/monitor/Monitor.tsx:291]: Shouldnt these all be inside a single `useEffect` hook?

**Review by comountainclimber — COMMENTED** [review]
Overall looks very good awesome job @endkeyCoder can we get the svg I linked in and then we can merge

**Comment by comountainclimber** [comment]
Also snapshot test in CI is failing can be fixed by running --updateSnapshot command https://jestjs.io/docs/cli#--updatesnapshot

File: src/pages/monitor/Monitor.tsx (hunk 3 above)
Comment (endkeyCoder) [reply src/pages/monitor/Monitor.tsx:291]: I don't think so, because each hook controls a part of the function's workflow, if you group everything on a single hook, it will alter the current flow and it will cause some bugs (I already tested it)

File: src/constants.tsx (hunk 1 above)
Comment (Thacryba) [reply src/constants.tsx:14]: I just fixed it in #277 
Once it is approved there, we'll make the rebase here.

**Comment by comountainclimber** [comment]
@endkeyCoder if we fix the failing test we can merge this in https://github.com/CityOfZion/dora/pull/293#issuecomment-817022833

**Comment by endkeyCoder** [comment]
> if we fix the failing test we can merge this in

I fixed it @comountainclimber :)

**Review by comountainclimber — APPROVED** [review]

**Comment by comountainclimber** [comment]
@endkeyCoder @Thacryba really nice job! I have approved feel free to merge whenever you would like 🍻
