### PR TITLE
CU-86ag4g36f - Dora - Fix color coded info on the Transaction Information page

### LINKED ISSUE #691: Fix color coded info on the Transaction Information page
The "DETAILS" section has a `sender` in purple, but hovering or clicking it doesn't do anything, I'd be good if it were to open a new tab with the sender's Address Information.
Image

Also, if the transaction is a NEO Transfer, the `mint` is purple and when hovering it seems clickable, but it does nothing. The Transactions section on the Address Information seems the way to go (with a white mint)
Ref: https://dora.coz.io/transaction/neo3/testnet/0x1c0248b783dcaf8df170f667450e0e6848b461c97a149a26de12fc58d2edcd3e
Image
Image

### PR DESCRIPTION
**Pull request by Thacryba**
close #691

### CODE REVIEW

File: src/components/transaction/TransactionN3.tsx [hunk 1]
```diff
@@ -29,9 +30,25 @@ export const TransactionN3: React.FC<Props> = ({
...
+  function handleAddressClick(address?: string) {
+    if (!isClickable(address)) {
+      return
+    }
+
+    const addressPath =
+      address === 'mint' ? 'NKuyBkoGdZZSLyPbJEetheRhMjeznFZszf' : address
+
+    navigate(`/address/${chain}/${network}/${addressPath}`)
+  }
```
Comment (hotequil) [inline src/components/transaction/TransactionN3.tsx]: You are repeating these code, create a hook called `useAddressNavigation`.

File: src/components/transaction/TransactionN3.tsx [hunk 2]
```diff
@@ -29,9 +30,25 @@ export const TransactionN3: React.FC<Props> = ({
   transfers,
 }) => {
   const width = useWindowWidth()
+  const navigate = useNavigate()
 
   const isMobileOrTablet = width <= 768
 
+  const isClickable = (address?: string) => {
```
Comment (hotequil) [inline src/components/transaction/TransactionN3.tsx]: Use
```suggestion
  const isAddressClickable = (address?: string) => {
```

File: src/components/transaction/TransactionN3.tsx [hunk 3]
```diff
@@ -29,9 +30,25 @@ export const TransactionN3: React.FC<Props> = ({
...
+    return !!address && address !== 'burn'
+  }
+
+  function handleAddressClick(address?: string) {
```
Comment (hotequil) [inline src/components/transaction/TransactionN3.tsx]: Use:

```suggestion
  function navigateToAddress(address?: string) {
```

File: src/components/transfer/Transfer.tsx [hunk 4]
```diff
@@ -95,10 +103,10 @@ const Transfer = ({ transfers = [], network, transaction, chain }: Props) => {
                     truncate
                     textOverflow={'clip'}
                     textAlign={'center'}
-                    color={'tertiary'}
+                    color={isClickable(transfer.from) ? 'tertiary' : 'white'}
                     mb={4}
                     onClick={() => handleAddressClick(transfer.from)}
-                    cursor={'pointer'}
+                    cursor={isClickable(transfer.from) ? 'pointer' : 'default'}
```
Comment (hotequil) [inline src/components/transfer/Transfer.tsx]: You are calling twice this method, create a variable.

File: src/components/transaction/TransactionN3.tsx [hunk 5]
```diff
@@ -75,11 +92,15 @@ export const TransactionN3: React.FC<Props> = ({
...
                 <Text
-                  color={'tertiary'}
+                  color={isClickable(transaction.sender) ? 'tertiary' : 'white'}
                   truncate
                   fontSize={'lg'}
                   fontWeight={600}
                   textAlign={['right', 'center']}
+                  onClick={() => handleAddressClick(transaction.sender)}
+                  cursor={
+                    isClickable(transaction.sender) ? 'pointer' : 'default'
```
Comment (hotequil) [inline src/components/transaction/TransactionN3.tsx]: The same.

**Review by hotequil — CHANGES_REQUESTED** [review]

**Review by hotequil — APPROVED** [review]
Ok!

**Comment by hotequil** [comment]
Hi, @ixje! Could I merge?

**Review by ixje — APPROVED** [review]
