### PR TITLE
Fix block search

### LINKED ISSUE #694: Search on block height and hash is broken
We can search on contract hash, transaction hash and address fine. But block searching has 2 problems

1. searching on block height (e.g. `1`) give no results
2. searching an exact block hash (e.g. `0xa16f95686272050b4958e3218ccbcd97ca1c571b1d438e130510e87d5a6db462`) goes to an empty block page at https://dora.coz.io/block/neo3/mainnet/0xa16f95686272050b4958e3218ccbcd97ca1c571b1d438e130510e87d5a6db462

   Image 

   - this is the wrong route. It should end up at https://dora.coz.io/block/neo3/mainnet/8849516
   - It also makes a wrong `GET` request specifically for "mainnet" ("testnet" is fine);  `https://dora.coz.io/api/v2/neo3/mainnet/block/6.687381075162338e+76` as observed in the dev console.
   - If you then press "home" 
      Image
   
      it will go to the homepage and you'll see that the "Blocks" list is empty
      Image

### PR DESCRIPTION
**Pull request by ixje**
close #694

### CODE REVIEW

File: src/pages/search-results/SearchResults.tsx [hunk 1]
```diff
@@ -170,14 +170,6 @@ const SearchResults: React.FC = () => {
 
       try {
         isSearchingRef.current = true
-
-        console.log({ state })
-
-        if (state?.results) {
```
Comment (hotequil) [inline src/pages/search-results/SearchResults.tsx:176]: I think it's better keep it. Because this code receives the results from `<Search />`. If there isn't any data, it try to search using the below code.

Just remove the `console.log`.

**Review by hotequil — CHANGES_REQUESTED** [review]
Search isn't working with all blocks.
Image

File: src/pages/search-results/SearchResults.tsx (hunk 1 above)
Comment (ixje) [reply src/pages/search-results/SearchResults.tsx:176]: I returned it. Now that the validation functions are fixed this code no longer seems to prevent the results from showing

File: src/hooks/useBlockchainSearch.ts [hunk 2]
```diff
@@ -50,7 +56,13 @@ const options: SearchOptions[] = [
     network: 'mainnet',
     type: 'block',
     fetchFn: (text: string) => NeoRest.block(text as any, 'mainnet'),
-    validateFn: (text: string) => u.isHex(u.remove0xPrefix(text)),
+    validateFn: (text: string) => {
+      const blockNr = Number.parseInt(text, 10)
```
Comment (hotequil) [inline src/hooks/useBlockchainSearch.ts]: Use:
```suggestion
      const blockNumber = parseInt(text)
```

File: src/hooks/useBlockchainSearch.ts [hunk 3]
```diff
@@ -22,7 +22,13 @@ const options: SearchOptions[] = [
     network: 'testnet',
     type: 'block',
     fetchFn: (text: string) => NeoRest.block(text as any, 'testnet'),
-    validateFn: (text: string) => u.isHex(u.remove0xPrefix(text)),
+    validateFn: (text: string) => {
+      const blockNr = Number.parseInt(text, 10)
```
Comment (hotequil) [inline src/hooks/useBlockchainSearch.ts]: Use:

```suggestion
      const blockNumber = parseInt(text)
```

**Review by hotequil — CHANGES_REQUESTED** [review]

File: src/hooks/useBlockchainSearch.ts (hunk 2 above)
Comment (ixje) [reply src/hooks/useBlockchainSearch.ts]: I kept the radix because there is a warning in the `parseInt` docs

>  If 0 or not provided, the radix will be inferred based on string's value. Be careful — this does not always default to 10!

I therefore think it's important to make this explicit

**Review by hotequil — APPROVED** [review]
Ok!
