### PR TITLE
CU-86ag4vtgg - Dora - Fix decimal numbers

### LINKED ISSUE #701: Fix decimal numbers
When we have a bigger number, we should format the number correctly:
Image

### PR DESCRIPTION
**Pull request by Thacryba**
close #701

### CODE REVIEW

File: src/utils/formatter.ts [hunk 1]
```diff
@@ -47,3 +47,10 @@ export const uuid = () => {
   const numbers = Math.random().toString(36)
   return date + numbers
 }
+
+export const formatAmount = (amount: string | number) => {
+  if (!amount && amount !== 0) return '0'
```
Comment (hotequil) [inline src/utils/formatter.ts]: Use:
```suggestion
  if (!amount && amount != 0) return '0'
```
To allow `'0'` or `0`.

**Review by hotequil — CHANGES_REQUESTED** [review]

**Review by hotequil — APPROVED** [review]
Ok!

**Comment by hotequil** [comment]
Hi, @ixje! Could I merge?

File: src/utils/formatter.ts [hunk 2]
```diff
@@ -47,3 +47,10 @@ export const uuid = () => {
   const numbers = Math.random().toString(36)
   return date + numbers
 }
+
+export const formatAmount = (amount: string | number) => {
+  if (!amount && amount != 0) return '0'
+
+  const bigNumber = toBigNumber(amount)
+  return bigNumber.toFixed()
```
Comment (ixje) [inline src/utils/formatter.ts:55]: I haven't checked, but my main concern is loss of precision.
1. will it round up/down? if so, to how many decimals?
2. if it does not round, will it cut off at `i` decimals? if so, what is `i`

Comment (Thacryba) [reply src/utils/formatter.ts:55]: I tested with a really small number, more than 100 decimal places and it neither round nor cut off
I also talked with Lucas and Raul and they said it would be better if there was the Symbol listed instead of the name, what do you think? I added this to the code as well as some other places that can show the notation, but I can change it back if you don't want it

File: src/components/transfer/Transfer.tsx [hunk 3]
```diff
@@ -273,8 +274,10 @@ const Transfer = ({ transfers = [], network, transaction, chain }: Props) => {
                   </Text>
                   <Flex className="transfer-amount-container" mb={2}>
                     {getTransferLogo(transfer.symbol, chain)}
-                    <Text>{transfer.amount}</Text>
-                    <Text>{transfer.name}</Text>
+                    <Text
+                      maxW={'inherit'}
+                      wordBreak={'break-all'}
+                    >{`${formatAmount(transfer.amount)} ${transfer.symbol}`}</Text>
```
Comment (hotequil) [inline src/components/transfer/Transfer.tsx]: Use:
```suggestion
                    >{formatAmount(transfer.amount)} {transfer.symbol}</Text>
```

File: src/components/transfer/Transfer.tsx [hunk 4]
```diff
@@ -105,8 +105,9 @@ const Transfer = ({ transfers = [], network, transaction, chain }: Props) => {
                   </Text>
                   <Flex className="transfer-amount-container" mb={2}>
                     {getTransferLogo(transfer.symbol, chain)}
-                    <Text>{transfer.amount}</Text>
-                    <Text>{transfer.name}</Text>
+                    <Text maxW={'inherit'} wordBreak={'break-all'}>
+                      {`${formatAmount(transfer.amount)} ${transfer.symbol}`}
```
Comment (hotequil) [inline src/components/transfer/Transfer.tsx]: Use:

```suggestion
                      {formatAmount(transfer.amount)} {transfer.symbol}
```

**Review by hotequil — CHANGES_REQUESTED** [review]

File: src/utils/formatter.ts (hunk 2 above)
Comment (ixje) [reply src/utils/formatter.ts:55]: > I tested with a really small number, more than 100 decimal places and it neither round nor cut off 

Thanks. Then that part is fine with me. 

> I also talked with Lucas and Raul and they said it would be better if there was the Symbol listed instead of the name, what do you think? I added this to the code as well as some other places that can show the notation, but I can change it back if you don't want it

Let's not do that for the time being. That's a bigger design change we might want to run by the design team first and outside of the scope of this PR

**Comment by ixje** [comment]
@hotequil your description in #701 doesn't link an actual transaction that shows the issue, so I can't cross check on this branch. I tried to find one but couldn't. If you think the PR solves it, then I'm ok with it as well.

**Review by hotequil — APPROVED** [review]
Ok!

**Comment by hotequil** [comment]
Hi, @ixje! It's okay for me:
Screenshot 2026-03-17 at 09 01 24

You can run the locally and access: http://localhost:5173/transaction/neo3/mainnet/0x49ffbc72fa6016edec9bbb995ed7609d2bd5aabc87bb25cd88f80af1e11576d9.

Could I merge?
