### PR TITLE
fix nep-17 transfer if amount is bytestring

### LINKED ISSUE #598: Incorrect display of transfer amount when type is bytestring
The third transfer in this transaction should be 8 Ghostmarket tokens but Dora shows 0:
https://dora.coz.io/transaction/neo3/testnet/0xa9b61e6a8cc0b8b6d958e8576013ddeaf0179ec8630b486d78b427f074c04c47

The meta indexer shows the correct amount, as well as Neotube:
https://n3t5.neotube.io/transaction/0xa9b61e6a8cc0b8b6d958e8576013ddeaf0179ec8630b486d78b427f074c04c47

It appears that the Dora UI is not correctly displaying the transfer due to the amount being encoded as a bytestring instead of an integer.

### PR DESCRIPTION
**Pull request by ixje**
fixes https://github.com/CityOfZion/dora/issues/598

This fixes 2 parts
1. The changes in `Transaction.tsx` fixes this
Screenshot 2022-11-07 at 10 52 33
2. The changes in `Notification.tsx` fixes this
 Screenshot 2022-11-07 at 11 19 13

### CODE REVIEW

File: src/components/transaction/notification/Notification.tsx [hunk 1]
```diff
@@ -23,6 +24,26 @@ export const Notification: React.FC<{
     {},
   )
 
+  //fix for NEP-17 contract that emit transfer events with ByteString as amount
+  for (const notification of notifications) {
+    if (notification.state.type === 'Array') {
+      const isTransfer = notification.event_name === 'Transfer'
+
+      if (isTransfer) {
+        const bytestringNotification = notification.state.value[2]
```
Comment (ixje) [inline src/components/transaction/notification/Notification.tsx]: the transfer `amount` is always the 3rd element

File: src/components/transaction/notification/Notification.tsx [hunk 2]
```diff
@@ -23,6 +24,25 @@ export const Notification: React.FC<{
...
   )
 
+  //fix for NEP-17 contract that emit transfer events with ByteString as amount
+  for (const notification of notifications) {
+    if (notification.state.type === 'Array') {
+      const isTransfer = notification.event_name === 'Transfer'
+
+      if (isTransfer) {
+        const amountStackItem = notification.state.value[2]
+        if (amountStackItem.type === 'ByteString') {
```
Comment (comountainclimber) [inline src/components/transaction/notification/Notification.tsx:34]: Do we need optional chaining here to prevent a type error in case `amountStackItem` is undefined???

`    if (amountStackItem?.type === 'ByteString') {`

File: src/pages/transaction/Transaction.tsx [hunk 3]
```diff
@@ -112,10 +113,28 @@ const parseNeo3TransactionData = async (
...
             value => value.type === 'Integer',
           )
-          const amount = integerNotfication ? integerNotfication.value : 0
+          if (integerNotification) {
+            amount = integerNotification.value as unknown as number
+          } else {
+            // fix for contracts that don't adhere to NEP-17 standard
+            // and emit ByteString instead of Integer
+            const amountStackItem = notification.state.value[2]
+            if (amountStackItem.type === 'ByteString') {
```
Comment (comountainclimber) [inline src/pages/transaction/Transaction.tsx:126]: See comment above

File: src/components/transaction/notification/Notification.tsx (hunk 2 above)
Comment (ixje) [reply src/components/transaction/notification/Notification.tsx:34]: it cannot be undefined

**Review by comountainclimber — APPROVED** [review]

**Comment by ixje** [comment]
thnx!

**Comment by melanke** [comment]
Task linked: [CU-36gv3bp Accept ByteString as amount for NEP-17](https://app.clickup.com/t/36gv3bp)

**Comment by melanke** [comment]
Task linked: [CU-3ccf1tb fix nep-17 transfer if amount is bytestring](https://app.clickup.com/t/3ccf1tb)
